site_name: Samantha Roberts, PhD - WorldlyCode LLC
site_description: Documentation for WorldlyCode LLC
site_url: https://srobertsphd.github.io
repo_name: srobertsphd.github.io

# Standard docs directory
docs_dir: docs

theme:
  name: material
  font: 
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: octicons/globe/16
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    # - navigation.expand
    - navigation.collapsible
    - navigation.instant
    # - toc.integrate # toggle OFF to show the toc on the right side of the page
    - search.suggest
    - search.highlight
    - navigation.top

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
      # baselevel: 2
      # separator: "_"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
#  - awesome-pages


nav:
  - Home: index.md
#   - Signup:
#     - Signup Overview: signup/index.md
#   - Lab Policies:
#     - Lab Policies Overview: policy/index.md
#     - Rules of Conduct: policy/conduct.md
#     - Safety: policy/safety.md
#     - C-14 | After Hours Access: policy/c14.md
#   - Tool SOPs: 
#     - Tool SOP Overview: tool_sops/index.md
#     - Lithography SOPs:
#       - Lithography SOPs Overview: tool_sops/lithography_sops/index.md
#       - Elionix EBL 100keV: tool_sops/lithography_sops/elionix_100.md
#       - WECAS Software: tool_sops/lithography_sops/wecas.md
#     - Etcher SOPs:
#       - Etcher SOP Overview: tool_sops/etch_sops/index.md
#       - RIE Etcher: tool_sops/etch_sops/rie.md
#       - ICP Flourine Etcher: tool_sops/etch_sops/icp-fl.md
#       - ICP Chlorine Etcher: tool_sops/etch_sops/icp-cl.md
#   - Chemicals:
#     - Chemical SOPs: 
#       - Chemical SOP Overview: chemicals/chem_sops/index.md
#       - Aluminum Etch: chemicals/chem_sops/aluminum_etch.md
#       - Piranha Clean: chemicals/chem_sops/piranha.md
#       - RCA Clean: chemicals/chem_sops/rca_clean.md
#       - Nickel Etch: chemicals/chem_sops/nickel_etch.md
#       - Chromium Etch: chemicals/chem_sops/chrome_etch.md
#       - Hydrofluoric Acid: chemicals/chem_sops/hf_etch.md
#     - Chemical List | SDS:
#       - Chemical List | SDS Overview: chemicals/chem_sds/index.md
#   - FAQ:
#     - FAQ Overview: faq/index.md
#   - Staff-Info: 
#     - Staff Info Overview: staff/index.md
#     - Google Drive: staff/google.md
#     - SOP Formatting: staff/sop_formatting.md
#     - Document Versioning: staff/versioning.md
#     - Mkdocs Setup: staff/mkdocs-setup.md
#     - Links: staff/links.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sprobertsphd/srobertsphd.github.io
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/worldlycode/
# extra_css:
#   - stylesheets/extra.css

copyright: "© 2025 WorldlyCode LLC"