site_name: Samantha Roberts, PhD - WorldlyCode LLC
site_description: Documentation for WorldlyCode LLC
site_url: https://srobertsphd.github.io/
repo_name: srobertsphd.github.io

# Standard docs directory
docs_dir: docs

theme:
  name: material
  font: 
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: octicons/globe/16
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    # - navigation.expand
    - navigation.collapsible
    - navigation.instant
    - content.action.edit
    # - toc.integrate # toggle OFF to show the toc on the right side of the page
    - search.suggest
    - search.highlight
    - navigation.top

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
      # baselevel: 2
      # separator: "_"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
  - awesome-pages
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: long
      post_url_format: "{date}/{slug}"
      pagination: true
      pagination_per_page: 5
      # Disable archive and categories in navigation
      archive: false
      categories: false
      # Keep them accessible via URLs
      archive_name: "Past Posts"
      archive_date_format: "yyyy"
      archive_url_format: "archive/{date}"
      categories_name: "Topics"
      categories_url_format: "topics/{slug}"
      categories_toc: false
      # Custom templates
      archive_template: "blog/templates/archive.html"
      category_template: "blog/templates/category.html"

nav:
  - Home: index.md
  - Blog: blog/index.md
  - MkDocs:
    - Overview: mkdocs/index.md
    - Feature Cards Guide: mkdocs/feature-cards-guide.md
    - Feature Cards Examples: mkdocs/feature-cards-examples.md
    - Cursor Help: mkdocs/cursor-help.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/srobertsphd/srobertsphd.github.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samantha-roberts-phd/
    - icon: fontawesome/solid/globe
      link: https://samantharoberts.com
      name: Samantha Roberts, PhD
      title: WorldlyCode LLC
extra_css:
  - assets/stylesheets/blog-custom.css

copyright: "© 2025 WorldlyCode LLC"